// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqfnevosdxzlbuimhkap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZm5ldm9zZHh6bGJ1aW1oa2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3ODQwMTYsImV4cCI6MjA3NDM2MDAxNn0.W_fqYFCFH9irfeXMwpizReW_5qUqz7wpQq3-7sIvljQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});